import { BrowserWindow } from 'electron'

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

export function createMainWindow() {
  const window = new BrowserWindow({
    width: 520,
    height: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    icon: './resources/app/.webpack/main/images/icon.png',
  })

  window.setMenuBarVisibility(false)
  void window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

  if (process.env.NODE_ENV === 'development') {
    setTimeout(() => {
      window.show()
      window.focus()
      window.center()
      window.moveTop()
      // window.setBounds({ x: 2554, y: 0, width: 520, height: 720 }, true)
      // window.webContents.openDevTools()
    }, 50)
  }

  return window
}
